@startuml
class FocusInfos {
{field}focus_start_time : long
{field}focus_end_time : long
{field}normalized_score : double
{field}maxScore : double
{field}minScore : double
{field}dict_score : Dictionary<string, double>
{field}dict_score_weight : Dictionary<string, double>

{method}GetTotalScore() : double
{method}Dict_score_weight() : Dictionary<string, double>
{method}Dict_score_weight(dict_score_weight:Dictionary<string, double>) : void
{method}Focus_start_time() : long
{method}Focus_start_time(focus_start_time:long) : void
{method}Focus_end_time() : long
{method}Focus_end_time(focus_end_time:long) : void
{method}Normalized_score() : double
{method}Normalized_score(normalized_score:double) : void
{method}MaxScore() : double
{method}MaxScore(maxScore:double) : void
{method}MinScore() : double
{method}MinScore(minScore:double) : void
}
@enduml